#!/bin/bash
# Version 4

# plasmapkg2 -u package
# plasmawindowed $(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")

rm ~/.cache/plasma-svgelements-*
killall plasmoidviewer
plasmoidviewer -a package -l topedge -f horizontal -x 0 -y 0
# QT_DEVICE_PIXEL_RATIO=2 plasmoidviewer -a package -l floating -f horizontal
