#!/bin/bash

# Function to check if a command was successful
check_command_success() {
        if [ "$1" != "0" ]; then
                echo "Error executing command: $2"
                exit 1
        fi
}

# Parse arguments for restart option
restartPlasmashell=false
for arg in "$@"; do
        case "$arg" in
                -r|--restart) restartPlasmashell=true;;
                *) ;;
        esac
done

# Determine if the package is already installed
packageNamespace=$(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
packageServiceType=$(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-ServiceTypes")
kpackagetool5 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
isAlreadyInstalled=$?

# Convert metadata.desktop to metadata.json
if command -v desktoptojson &> /dev/null ; then
        desktoptojson --serviceType="plasma-applet.desktop" -i "$PWD/package/metadata.desktop" -o "$PWD/package/metadata.json"
        check_command_success "$?" "desktoptojson conversion failed"
        sed -i '{s/ \{4\}/\t/g}' "$PWD/package/metadata.json" # Tabify metadata.json
fi

# Install or update the package
if [ "$isAlreadyInstalled" == "0" ]; then
        kpackagetool5 -t "${packageServiceType}" -u package
        restartPlasmashell=true
else
        kpackagetool5 -t "${packageServiceType}" -i package
fi

# Restart Plasma shell if required
if $restartPlasmashell; then
        killall plasmashell
        ( cd $HOME && kstart5 plasmashell )
fi
