#!/bin/bash
# Version 4

killall plasmoidviewer

# plasmapkg2 -u package
# plasmawindowed $(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")

# plasmoidviewer -a package -l bottomedge -f horizontal -s 400x200
# plasmoidviewer -a package -l bottomedge -f horizontal -x 0 -y 0 -s 200x80 -c org.kde.panel
# plasmoidviewer -a package -l floating -f horizontal -x 0 -y 0 -s 900x600
QT_DEVICE_PIXEL_RATIO=2 plasmoidviewer -a package -l floating -f horizontal -x 0 -y 0 -s 1920x1080
