#!/bin/bash
# Version 3

packageServiceType=`kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-ServiceTypes"`

# Eg: kpackagetool5 -t "Plasma/Applet" -r package
kpackagetool5 -t "${packageServiceType}" -r package
