#!/bin/bash
# Version 4

# plasmapkg2 -u package
# plasmawindowed $(kreadconfig --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")

killall plasmoidviewer
plasmoidviewer -a package -l bottomedge -f horizontal
# plasmoidviewer -a package -l leftedge -f vertical
# plasmoidviewer -a package -l floating -f planar
